#config_version=3

show_player:
    mode_attract_started:
      - show: attract_dmd_loop
        repeat: yes
        tocks_per_sec: 1

light_player:
    mode_attract_started:
      - show: vendor_bottom_fade_rainbow
        repeat: yes
      - show: vendor_left_fade_rainbow
        repeat: yes
      - show: photos_arrow_chase_rainbow
        repeat: yes
      - show: spinner_arrow_chase_rainbow
        repeat: yes
#      - show: left_kickout_chase_rainbow
#        repeat: yes
#      - show: right_kickout_chase_rainbow
#        repeat: yes

