#config_version=3

show_player:
    mode_attract_started:
      - show: attract_dmd_loop
        repeat: yes
        tocks_per_sec: 1

light_player:
    mode_attract_started:
      - show: vendor_bottom_fade_rainbow
        repeat: yes
      - show: main_stage_arrow_0_chase_rainbow
        repeat: yes

