#config_version=3

show_player:
    mode_attract_started:
      - show: attract_dmd_loop
        repeat: yes
        tocks_per_sec: 1

light_player:
    mode_attract_started:
      - show: attract_light_show
        repeat: yes
        tocks_per_sec: 48

