# config_version=3

mode:
  start_events: photos_selected
  stop_events: timer_mode_cooldown_complete
  priority: 100

logic_blocks:
  sequences:
    photos:
      events: s_fixedTarget_post_inline_active
      reset_events: mode_photos_stopping

timers:
  mode_cooldown:
    end_value: 4
    control_events:
      - event: logicblock_photos_complete
        action: start

show_player:
    s_fixedTarget_post_inline_active:
      - show: peanut_butter_jelly_time
        tocks_per_sec: 1
