#config_version=3

config:
    - hardware.yaml
    - switches.yaml
    - coils.yaml
    - devices.yaml
    - dmd.yaml
    - targets.yaml
    - lights.yaml
    - shots.yaml
    - modes.yaml
    - light_scripts.yaml

fonts:
    weltron:
        file: WELTRON2.TTF

scriptlets:
    carousel_mode_complete_handler.CarouselModeCompleteHandler

bcp:
    connections:
        local_display:
            host: localhost
            port: 5050
            connection_attempts: 5
            require_connection: yes
