#config_version=3

config:
    - hardware.yaml
    - switches.yaml
    - coils.yaml
    - devices.yaml
    - dmd.yaml
    - targets.yaml
    - lights.yaml
    - shots.yaml

modes:
    - base

fonts:
    weltron:
        file: WELTRON2.TTF

scriptlets:
    bumper_counter.BumperCounter

bcp:
    connections:
        local_display:
            host: localhost
            port: 5050
            connection_attempts: 5
            require_connection: yes
