#config_version=3

smartmatrix:
    port: /dev/ttyACM0
    use_separate_thread: yes
    
dmd:
    physical: yes
#    physical: no
    width: 128
    height: 32
    type: color

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2
      - type: text
        font: tall title
        text: NELSON
        h_pos: center
        v_pos: top
        y: 60
        size: 100
        antialias: yes
        layer: 1
        color: ee9900
