#config_version=3

leds:
    l_vendor_bottom_a: { number: 0 }
    l_vendor_bottom_b: { number: 1 }
    l_vendor_bottom_c: { number: 2 }
    l_vendor_bottom_d: { number: 3 }
    l_vendor_bottom_e: { number: 4 }
    l_vendor_bottom_f: { number: 5 }
    l_vendor_bottom_g: { number: 6 }
    l_vendor_bottom_h: { number: 7 }
    l_vendor_bottom_i: { number: 8 }
    l_vendor_bottom_j: { number: 9 }
    l_vendor_bottom_k: { number: 10 }
    l_vendor_bottom_l: { number: 11 }
    
    l_vendor_left_a: { number: 12 }
    l_vendor_left_b: { number: 13 }
    l_vendor_left_c: { number: 14 }
    l_vendor_left_d: { number: 15 }
    l_vendor_left_e: { number: 16 }
    l_vendor_left_f: { number: 17 }
    l_vendor_left_g: { number: 18 }
    l_vendor_left_h: { number: 19 }
    l_vendor_left_i: { number: 20 }
    l_vendor_left_j: { number: 21 }
    l_vendor_left_k: { number: 22 }
    l_vendor_left_l: { number: 23 }
    
    l_vendor_right_a: { number: 511 }
    l_vendor_right_b: { number: 511 }
    l_vendor_right_c: { number: 511 }
    l_vendor_right_d: { number: 511 }
    l_vendor_right_e: { number: 511 }
    l_vendor_right_f: { number: 511 }
    l_vendor_right_g: { number: 511 }
    l_vendor_right_h: { number: 511 }
    l_vendor_right_i: { number: 511 }
    l_vendor_right_j: { number: 511 }
    l_vendor_right_k: { number: 511 }
    l_vendor_right_l: { number: 511 }
    
    l_admissions_1: { number: 24 }
    l_admissions_2: { number: 25 }
    l_admissions_3: { number: 26 }
    
    l_main_stage_edge_a: { number: 27 }
    l_main_stage_edge_b: { number: 28 }
    l_main_stage_edge_c: { number: 29 }
    l_main_stage_edge_d: { number: 30 }
    l_main_stage_edge_e: { number: 31 }
    l_main_stage_edge_f: { number: 32 }
    l_main_stage_edge_g: { number: 33 }
    l_main_stage_edge_h: { number: 34 }
    l_main_stage_edge_i: { number: 35 }
    l_main_stage_edge_j: { number: 36 }
    l_main_stage_edge_k: { number: 37 }
    l_main_stage_edge_l: { number: 38 }
    l_main_stage_edge_m: { number: 39 }
    
    l_main_stage_arrow_0_a: { number: 511 }
    l_main_stage_arrow_0_b: { number: 511 }
    l_main_stage_arrow_0_c: { number: 511 }
    l_main_stage_arrow_0_d: { number: 511 }
    l_main_stage_arrow_0_e: { number: 511 }
    l_main_stage_arrow_0_f: { number: 511 }
    l_main_stage_arrow_0_g: { number: 511 }
    l_main_stage_arrow_0_h: { number: 511 }
    
    l_main_stage_arrow_1_a: { number: 511 }
    l_main_stage_arrow_1_b: { number: 511 }
    l_main_stage_arrow_1_c: { number: 511 }
    l_main_stage_arrow_1_d: { number: 511 }
    l_main_stage_arrow_1_e: { number: 511 }
    l_main_stage_arrow_1_f: { number: 511 }
    l_main_stage_arrow_1_g: { number: 511 }
    l_main_stage_arrow_1_h: { number: 511 }
    
    l_main_stage_arrow_2_a: { number: 511 }
    l_main_stage_arrow_2_b: { number: 511 }
    l_main_stage_arrow_2_c: { number: 511 }
    l_main_stage_arrow_2_d: { number: 511 }
    l_main_stage_arrow_2_e: { number: 511 }
    l_main_stage_arrow_2_f: { number: 511 }
    l_main_stage_arrow_2_g: { number: 511 }
    l_main_stage_arrow_2_h: { number: 511 }
    
    l_xp_multiplier_2_a: { number: 91 }
    l_xp_multiplier_2_b: { number: 92 }
    l_xp_multiplier_2_c: { number: 93 }
    l_xp_multiplier_2_d: { number: 94 }
    l_xp_multiplier_2_e: { number: 95 }
    l_xp_multiplier_2_f: { number: 96 }
    l_xp_multiplier_2_g: { number: 97 }
    
    l_xp_multiplier_3_a: { number: 98 }
    l_xp_multiplier_3_b: { number: 99 }
    l_xp_multiplier_3_c: { number: 100 }
    l_xp_multiplier_3_d: { number: 101 }
    l_xp_multiplier_3_e: { number: 102 }
    l_xp_multiplier_3_f: { number: 103 }
    l_xp_multiplier_3_g: { number: 104 }
    
    l_xp_multiplier_5_a: { number: 105 }
    l_xp_multiplier_5_b: { number: 106 }
    l_xp_multiplier_5_c: { number: 107 }
    l_xp_multiplier_5_d: { number: 108 }
    l_xp_multiplier_5_e: { number: 109 }
    l_xp_multiplier_5_f: { number: 110 }
    l_xp_multiplier_5_g: { number: 111 }
    
    l_spinner_arrow_a: { number: 79 }
    l_spinner_arrow_b: { number: 78 }
    l_spinner_arrow_c: { number: 77 }
    l_spinner_arrow_d: { number: 76 }
    l_spinner_arrow_e: { number: 75 }
    l_spinner_arrow_f: { number: 74 }
    l_spinner_arrow_g: { number: 73 }
    l_spinner_arrow_h: { number: 72 }
    
    l_photos_arrow_a: { number: 71 }
    l_photos_arrow_b: { number: 70 }
    l_photos_arrow_c: { number: 69 }
    l_photos_arrow_d: { number: 68 }
    l_photos_arrow_e: { number: 67 }
    l_photos_arrow_f: { number: 66 }
    l_photos_arrow_g: { number: 65 }
    l_photos_arrow_h: { number: 64 }
    
    l_gaming_drop_target_0: { number: 114 }
    l_gaming_drop_target_1: { number: 113 }
    l_gaming_drop_target_2: { number: 112 }
    
    l_xp_bar_a: { number: 511 }
    l_xp_bar_b: { number: 511 }
    l_xp_bar_c: { number: 511 }
    l_xp_bar_d: { number: 511 }
    l_xp_bar_e: { number: 511 }
    l_xp_bar_f: { number: 511 }
    l_xp_bar_g: { number: 511 }
    l_xp_bar_h: { number: 511 }
    
    l_other_bar_0_a: { number: 511 }
    l_other_bar_0_b: { number: 511 }
    l_other_bar_0_c: { number: 511 }
    l_other_bar_0_d: { number: 511 }
    l_other_bar_0_e: { number: 511 }
    l_other_bar_0_f: { number: 511 }
    l_other_bar_0_g: { number: 511 }
    l_other_bar_0_h: { number: 511 }
    
    l_other_bar_1_a: { number: 511 }
    l_other_bar_1_b: { number: 511 }
    l_other_bar_1_c: { number: 511 }
    l_other_bar_1_d: { number: 511 }
    l_other_bar_1_e: { number: 511 }
    l_other_bar_1_f: { number: 511 }
    l_other_bar_1_g: { number: 511 }
    l_other_bar_1_h: { number: 511 }
    
    l_cosplay_drop_target_0: { number: 82 }
    l_cosplay_drop_target_1: { number: 81 }
    l_cosplay_drop_target_2: { number: 80 }
    
    l_left_kickout_arrow_a: { number: 122 }
    l_left_kickout_arrow_b: { number: 121 }
    l_left_kickout_arrow_c: { number: 120 }
    l_left_kickout_arrow_d: { number: 119 }
    l_left_kickout_arrow_e: { number: 118 }
    l_left_kickout_arrow_f: { number: 117 }
    l_left_kickout_arrow_g: { number: 116 }
    l_left_kickout_arrow_h: { number: 115 }
    
    l_right_kickout_arrow_a: { number: 90 }
    l_right_kickout_arrow_b: { number: 89 }
    l_right_kickout_arrow_c: { number: 88 }
    l_right_kickout_arrow_d: { number: 87 }
    l_right_kickout_arrow_e: { number: 86 }
    l_right_kickout_arrow_f: { number: 85 }
    l_right_kickout_arrow_g: { number: 84 }
    l_right_kickout_arrow_h: { number: 83 }
    
    l_gaming_mode_a: { number: 511 }
    l_gaming_mode_b: { number: 511 }
    l_gaming_mode_c: { number: 511 }
    
    l_vendor_mode_a: { number: 511 }
    l_vendor_mode_b: { number: 511 }
    l_vendor_mode_c: { number: 511 }
    
    l_auction_mode_a: { number: 511 }
    l_auction_mode_b: { number: 511 }
    l_auction_mode_c: { number: 511 }
    
    l_photo_mode_a: { number: 511 }
    l_photo_mode_b: { number: 511 }
    l_photo_mode_c: { number: 511 }
    
    l_cosplay_mode_a: { number: 511 }
    l_cosplay_mode_b: { number: 511 }
    l_cosplay_mode_c: { number: 511 }
    
    l_stargazer_mode_a: { number: 511 }
    l_stargazer_mode_b: { number: 511 }
    l_stargazer_mode_c: { number: 511 }
    
    l_extra_ball_a: { number: 511 }
    l_extra_ball_b: { number: 511 }
    l_extra_ball_c: { number: 511 }
    l_extra_ball_d: { number: 511 }
    l_extra_ball_e: { number: 511 }
    l_extra_ball_f: { number: 511 }
    l_extra_ball_g: { number: 511 }
    l_extra_ball_h: { number: 511 }
    
    l_jackpot_a: { number: 511 }
    l_jackpot_b: { number: 511 }
    l_jackpot_c: { number: 511 }
    l_jackpot_d: { number: 511 }
    l_jackpot_e: { number: 511 }
    l_jackpot_f: { number: 511 }
    l_jackpot_g: { number: 511 }
    l_jackpot_h: { number: 511 }
    
    l_multiball_a: { number: 511 }
    l_multiball_b: { number: 511 }
    l_multiball_c: { number: 511 }
    l_multiball_d: { number: 511 }
    l_multiball_e: { number: 511 }
    l_multiball_f: { number: 511 }
    l_multiball_g: { number: 511 }
    l_multiball_h: { number: 511 }
    
    l_left_outlane: { number: 511 }
    l_left_inlane: { number: 511 }
    l_right_inlane: { number: 511 }
    l_right_outlane: { number: 511 }
    
    l_ball_save_a: { number: 511 }
    l_ball_save_b: { number: 511 }
    l_ball_save_c: { number: 511 }
    l_ball_save_d: { number: 511 }
    l_ball_save_e: { number: 511 }
    l_ball_save_f: { number: 511 }
    l_ball_save_g: { number: 511 }
    l_ball_save_h: { number: 511 }
    l_ball_save_i: { number: 511 }
    l_ball_save_j: { number: 511 }
    l_ball_save_k: { number: 511 }
    l_ball_save_l: { number: 511 }
