#config_version=3

shots:
    upperLane_1:
        switch: s_upperLane_1
        led: l_admissions_1
    upperLane_2:
        switch: s_upperLane_2
        led: l_admissions_2
    upperLane_3:
        switch: s_upperLane_3
        led: l_admissions_3

shot_groups:
    upperLanes:
        shots: upperLane_1, upperLane_2, upperLane_3