#config_version=3

keyboard:
    s:
        switch: s_start

switches:
    s_drain:
        number: 5-0

    s_trough1:
        number: 5-1

    s_trough2:
        number: 5-2

    s_trough3:
        number: 5-3

    s_start:
        number: 21-1
        tags: start

    s_flipper_left:
        number: 21-2
        tags: carousel_select_item

    s_flipper_right:
        number: 21-0
        tags: carousel_next_item

    s_outlane_right:
        number: 5-6

    s_inlane_right:
        number: 5-7

    s_inlane_left:
        number: 5-8

    s_outlane_left:
        number: 5-9

    s_plungerLane:
        number: 5-4

    s_dropTarget_left_3:
        number: 1-7

    s_dropTarget_left_2:
        number: 1-6

    s_dropTarget_left_1:
        number: 1-5

    s_upperLane_1:
        number: 10-7

    s_upperLane_2:
        number: 10-8

    s_upperLane_3:
        number: 10-9

    s_spinner:
        number: 10-0
        debounce_open: 5
        debounce_close: 5


    s_rubberSwitch_bottom:
        number: 10-6

    s_kickOut_left:
        number: 1-4

    s_popBumper_left:
        number: 10-2

    s_popBumper_bottom:
        number: 10-1

    s_popBumper_right:
        number: 10-3

    s_slingshot_right:
        number: 5-10
        
    s_slingshot_left:
        number: 5-11
        
    s_kickout_right:
        number: 1-0
        
    s_dropTarget_right_1:
        number: 1-1
        
    s_dropTarget_right_2:
        number: 1-2
        
    s_dropTarget_right_3:
        number: 1-3
        
    s_dropTarget_centre_1:
        number: 1-8
        
    s_dropTarget_centre_2:
        number: 1-9
        
    s_dropTarget_centre_3:
        number: 1-10
        
    s_rubberSwitch_side:
        number: 10-5
        
    s_fixedTarget_post_inline:
        number: 1-11
        
    s_mainStage_entry:
        number: 10-11
        tags: kingpyn_disable_pullup

    s_tilt:
        number: 21-7
        tags: tilt_warning

    s_slam_tilt:
        number: 21-8
        tags: slam_tilt