# config_version=3

config:
  - config.yaml

switch_player:
  start_event: mode_attract_started
  start_delay: 1s
  steps:
    - time: 100ms
      switch: s_trough1
      action: activate
    - time: 100ms
      switch: s_trough2
      action: activate
    - time: 100ms
      switch: s_trough3
      action: activate
    - time: 600ms
      switch: s_start
      action: hit
    - time: 100ms
      switch: s_trough3
      action: deactivate
    - time: 100ms
      switch: s_plungerLane
      action: activate
    - time: 1s
      switch: s_flipper_right
      action: hit
    - time: 1s
      switch: s_flipper_right
      action: hit
    - time: 1s
      switch: s_flipper_right
      action: hit
    - time: 1s
      switch: s_flipper_right
      action: hit
    - time: 1s
      switch: s_flipper_right
      action: hit
    - time: 1s
      switch: s_plungerLane
      action: deactivate
    - time: 1s
      switch: s_kickOut_left
      action: activate
    - time: 1s
      switch: s_trough2
      action: deactivate
    - time: 100ms
      switch: s_plungerLane
      action: activate
    - time: 1s
      switch: s_plungerLane
      action: deactivate
    - time: 1s
      switch: s_kickOut_right
      action: activate
    - time: 1s
      switch: s_trough1
      action: deactivate
    - time: 100ms
      switch: s_plungerLane
      action: activate
    - time: 1s
      switch: s_plungerLane
      action: deactivate
    - time: 1s
      switch: s_spinner
      action: hit
