# config_version=3

mode:
  start_events: gaming_selected
  stop_events: timer_mode_cooldown_complete
  priority: 100

shot_profiles:
  hit_me:
    states:
      - name: active
        light_script: flash_green
      - name: complete
        light_script: on_green

shots:
  gaming_drop_1:
    profile: hit_me
    reset_events: mode_gaming_stopping
  gaming_drop_2:
    profile: hit_me
    reset_events: mode_gaming_stopping
  gaming_drop_3:
    profile: hit_me
    reset_events: mode_gaming_stopping
  kickout_left:
    profile: hit_me
    enable_events: gamingDrops_hit_me_complete_complete
    reset_events: mode_gaming_stopping
  cosplay_kickout:
    profile: hit_me
    enable_events: gamingDrops_hit_me_complete_complete
    reset_events: mode_gaming_stopping

logic_blocks:
  accruals:
    gaming:
      events:
        - balldevice_kickout_left_ball_eject_attempt
        - balldevice_kickout_right_ball_eject_attempt
      enable_events: gamingDrops_hit_me_complete_complete
      reset_events: mode_gaming_stopping
      events_when_complete: carousel_mode_complete

timers:
  mode_cooldown:
    end_value: 4
    control_events:
      - event: carousel_mode_complete
        action: start

slide_player:
  gaming_selected:
    - type: text
      text: "GAMING BOTS!"
      expire: 3s
  gamingDrops_hit_me_complete_complete:
    - type: text
      text: "ROLL THE DICE!"
      expire: 3s